export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS' ;
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';

export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGUER_START';

export const START_LOADING = 'START_LOADING';
export const FINISHED_LOADING = 'FINISHED_LOADING';

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
