const actions = {
    UPDATE_INGREDIENTS: 'UPDATE_INGREDIENTS' ,
    UPDATE_PRICE: 'UPDATE_PRICE',
    UPDATE_ORDERS: 'UPDATE_ORDERS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED: 'PURCHASE_BURGER_FAILED',
    PURCHASE_BURGER_START: 'PURCHASE_BURGUER_START',
    START_LOADING: 'START_LOADING',
    FINISHED_LOADING: 'FINISHED_LOADING',
    PURCHASE_INIT: 'PURCHASE_INIT'
}


export default actions;